### ISSUE TITLE
train.sh not running 

### ISSUE THREAD

**Issue by Ashwanth-R** [rshaojimmy/MultiModal-DeepFake#25]
how to run the train.sh when using VScode it shows no command found but if i run in gitbash it shows 
$ sh train.sh
Traceback (most recent call last):
  File "train.py", line 18, in <module>v$ sh train.sh
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    import torch.nn as nn
  File "C:\Users\athen\anaconda3\envs\DGM4\lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "C:\Users\athen\anaconda3\envs\DGM4\lib\site-packages\torch\nn\modules\__init__.py", line 1, in <module>
    from .module import Module
  File "C:\Users\athen\anaconda3\envs\DGM4\lib\site-packages\torch\nn\modules\module.py", line 7, in <module>
    from ..parameter import Parameter
  File "C:\Users\athen\anaconda3\envs\DGM4\lib\site-packages\torch\nn\parameter.py", line 2, in <module>
    from torch._C import _disabled_torch_function_impl
ModuleNotFoundError: No module named 'torch._C'

I'm running this normal cpu I5 processor

**Comment by 0011szy** [comment]
你好你是怎么处理这个问题的呢
