### ISSUE TITLE
运行sh train.sh出现问题

### ISSUE THREAD

**Issue by FukangGuo** [rshaojimmy/MultiModal-DeepFake#41]
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    from models.HAMMER import HAMMER
  File "/root/code/MultiModal-DeepFake/models/HAMMER.py", line 3, in <module>
    from models.xbert import BertConfig, BertForMaskedLM, BertForTokenClassification
  File "/root/code/MultiModal-DeepFake/models/xbert.py", line 833, in <module>
    class BertModel(BertPreTrainedModel):
  File "/root/code/MultiModal-DeepFake/models/xbert.py", line 871, in BertModel
    @add_code_sample_docstrings(
TypeError: add_code_sample_docstrings() got an unexpected keyword argument 'tokenizer_class'
不清楚为什么

**Comment by Qishiyii** [comment]
你好，现在这个问题解决了吗？

**Comment by shy-001** [comment]
Creating dataset
Creating MAMMER
reshape position embedding from 196 to 256
_IncompatibleKeys(missing_keys=[], unexpected_keys=['head.weight', 'head.bias'])
Traceback (most recent call last):
  File "train.py", line 566, in <module>
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(args, config))
  File "/root/anaconda3/envs/DGM4_ser/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/anaconda3/envs/DGM4_ser/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/DGM4_ser/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/DGM4_ser/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/ai/li/root/code/MultiModal-DeepFake/train.py", line 394, in main_worker
    checkpoint = torch.load(args.checkpoint, map_location='cpu')
  File "/root/anaconda3/envs/DGM4_ser/lib/python3.8/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/anaconda3/envs/DGM4_ser/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
运行train.sh之后报错，请问有人知道这是为什么吗
