### ISSUE TITLE
Error in Training Codes with Default Distributed Setting as False

### ISSUE THREAD

**Issue by hellogeraldblah** [rshaojimmy/MultiModal-DeepFake#6]
I am trying out the training codes that you have provided. I am not using a distributed GPU system, here is the config I am using. 
*i converted the argparse code for the distributed argument to default to False 

But I have encountered this error: 
```
Start training
Traceback (most recent call last):
  File "train.py", line 561, in <module>
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(args, config))
  File "anaconda3/envs/DGM4/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "anaconda3/envs/DGM4/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "anaconda3/envs/DGM4/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "anaconda3/envs/DGM4/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "Github/MultiModal-DeepFake-root/MultiModal-DeepFake/train.py", line 416, in main_worker
    train_stats = train(args, model, train_loader, optimizer, tokenizer, epoch, warmup_steps, device, lr_scheduler, config, summary_writer)
  File "Github/MultiModal-DeepFake-root/MultiModal-DeepFake/train.py", line 141, in train
    loss_MAC, loss_BIC, loss_bbox, loss_giou, loss_TMG, loss_MLC = model(image, label, text_input, fake_image_box, fake_token_pos, alpha = alpha)
  File "/anaconda3/envs/DGM4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "Github/MultiModal-DeepFake-root/MultiModal-DeepFake/models/HAMMER.py", line 211, in forward
    self._dequeue_and_enqueue(image_feat_m, text_feat_m)
  File "anaconda3/envs/DGM4/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "Github/MultiModal-DeepFake-root/MultiModal-DeepFake/models/HAMMER.py", line 363, in _dequeue_and_enqueue
    image_feats = concat_all_gather(image_feat)
  File "anaconda3/envs/DGM4/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "Github/MultiModal-DeepFake-root/MultiModal-DeepFake/models/HAMMER.py", line 386, in concat_all_gather
    for _ in range(torch.distributed.get_world_size())]
  File "anaconda3/envs/DGM4/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 845, in get_world_size
    return _get_group_size(group)
  File "anaconda3/envs/DGM4/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 306, in _get_group_size
    default_pg = _get_default_group()
  File "anaconda3/envs/DGM4/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 410, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

Do correct me if im wrong, but I have already specified distributed to be False, why are the errors still referencing distributed codes?

Here is the change I made to argparse:
   ` parser.add_argument('--distributed', default=False, action='store_true')`

**Comment by rshaojimmy** [comment]
Hi, please also set args.launcher = 'none' and see if it works. Thanks.

**Comment by hellogeraldblah** [comment]
Hi, thank you for your reply.

I have tried setting the args.launcher = 'none' but it resulted in a `ValueError: Invalid launcher type`.

I believe the `init_dist(args)` function is throwing this error because it does not have a case for `'none'`.

May I know why did you suggest to set args.launcher = 'none' ?

Additionally, the stacktrace in the original issue was running using launcher = pytorch.

**Comment by rshaojimmy** [comment]
Hi,
if you set args.launcher == 'none', the programs will be run as follows:
if args.launcher == 'none':
    args.launcher = 'pytorch'
    main_worker(0, args, config)

The key is to let the program run on a single GPU (gpu No.0 for instance in  main_worker(0, args, config))
